### ISSUE TITLE
Add documentation / templates for cloud deployment

### ISSUE THREAD

**Issue by yuriburger** [thecloudnativewebapp/GoCloudNative.Bff#20]
It would be nice to have templates (Bicep, Terraform, CloudFormation) + documentation for Kubernetes on Azure or AWS deployment. Maybe initially just a "kickstarter" for the simplest architecture and expand on this with more advanced scenarios.

**Comment by thecloudnativewebapp** [comment]
I agree! On the documentation page (https://gocloudnative-bff.pages.dev/table-of-content/) I've listed two types of such templates:

> Integration Manuals
> ...
>  - Infrastructure
>    - Distributed apps
>      - Applying a BFF in an Azure Container Apps environment
>      - ___Applying a BFF in Kubernetes___
> ...

And also, I think, it would be helpful if these templates demonstrate how to deploy the BFF in a distributed way. It's been built with standard aspnetcore http sessions, and out-of-the-box you can use redis as session storage. 

This would mean we need to add the redis package to the Host app `dotnet add package Microsoft.Extensions.Caching.Redis`, and add the following line to the program.cs:

```csharp
// Add Distributed Redis Cache for Session
builder.Services.AddDistributedRedisCache(options =>
{
    options.Configuration = "localhost";
    options.InstanceName = "Session_";
});
```

(I must admit I haven't tested it yet. So if you run into something, let me know!)

Any idea what the template will look like exactly?

**Comment by yuriburger** [comment]
My first thoughts: Bicep for deployment in Azure Kubernetes Service. Both single and distributed scenario (so including Redis) and based on a private container registry. Let me work on an initial version so I can show you ;)

**Comment by thecloudnativewebapp** [comment]
By the way: Did you see the samples in the demo projects? https://github.com/thecloudnativewebapp/GoCloudNative.Bff/tree/main/docs/demos/IdentityServer4/src

You can find a working SPA and a working API here.

**Comment by appie2go** [comment]
Any updates on this?
