### ISSUE TITLE
.NET session is expiring too fast

### ISSUE THREAD

**Issue by zepa19** [thecloudnativewebapp/GoCloudNative.Bff#29]
Currently, I see that the [IdleTimeout](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.sessionoptions.idletimeout?view=aspnetcore-7.0#microsoft-aspnetcore-builder-sessionoptions-idletimeout) on the session is [set to 15 minutes](https://github.com/thecloudnativewebapp/GoCloudNative.Bff/blob/e7fbfacc32de2a0e56e9111ed0cd516de911d98a/src/GoCloudNative.Bff.Authentication/ModuleInitializers/ModuleInitializer.cs#L34). 

**What that mean?**
When there is no request made in the last 15 minutes, the session data will be removed (access tokens, refresh tokens, etc), even if:
* the access token is still valid, so the requests should still be send with access token to the API
* the access token has expired, but we still have the refresh token, so new token can be retrieved

Currently, the session will be removed, so the entire redirection happen to the IdentityServer to get new auth code and then exchange it for a tokens.

This is bad UX in my opinion when every 15 minutes of inactivity, we need go throught the authentication process again, specially when the refresh tokens have long durations (days to even months). Until the refresh token is valid, the session should stay as it is. Only when the refresh token is revoked or expired, then the session can be removed.

**Ideas**
First of all, I am not experienced with sessions in .net, so I don't know whether my ideas will work, or even are possible to do at all.

Option 1
The session should have the same lifetime as the refresh token. It should be removed when the refresh token expires or is revoked. If no refresh token is available in given solution, then use access token as a reference. The same goes with the cookie, that is sent to the browser.

Option 2
The easiest way to fix it is just to extend the IdleTimeout value. Even better when it will be possible to customize it via some options.

**Comment by appie2go** [comment]
Hi,

Thanks for your feedback. I think this is a very legit finding. I think there are two issues here:

1.) When the session expires, the tokens should be revoked
2.) The session timeout should be configurable.

The duration of a session depends on the application. In several cases I've worked on, the session timeout may not exceed 15 minutes. In other cases, these rules were not as strict. Therefor, i'll set the default to 15 minutes with an option to configure a custom value. This will allow you to set any expiry window you prefer.

Also, I will look for a way to revoke the tokens when the session expires.

Thanks very much,

Stay tuned

**Comment by thecloudnativewebapp** [comment]
Created pull request #35 

Samples and documentation will be updated accordingly.

**Comment by appie2go** [comment]
Hi,

I've just release v0.0.16. You can now configure the session idle timeout value by using the following code:

```csharp
builder.Services.AddSecurityBff(o =>
{
    // ...
    o.SessionIdleTimeout = TimeSpan.MaxValue;
    //...
});
```

When you implement this, you will also notice that the `AddSecurityBff` has been flagged obsolete. I'll write more about this, but in essence, in my opinion, things should be directly configurable from the config. The bootstrap has been simplified and can be done as follows:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "Bff": {
    "LandingPage": "/hello",
    "SessionIdleTimeout": "01:30:00",
    "Oidc": {
      "ClientId": "secret",
      "ClientSecret": "secret",
      "Authority": "https://login.foo.bar/"
    },
    "ReverseProxy": {
      "Routes": {
        "api": {
          "ClusterId": "api",
          "Match": {
            "Path": "/api/{*any}"
          }
        }
      },
      "Clusters": {
        "api": {
          "Destinations": {
            "api/node1": {
              "Address": "http://localhost:8080/"
            }
          }
        }
      }
    }
  }
}
```

and use this in the `program.cs`:

```csharp
using GoCloudNative.Bff.Authentication.ModuleInitializers;
using GoCloudNative.Bff.Authentication.OpenIdConnect;

var builder = WebApplication.CreateBuilder(args);

var config = builder.Configuration
    .GetSection("Bff")
    .Get<OidcBffConfig>();

builder.Services.AddBff(config);

var app = builder.Build();

app.UseBff();

app.Run();

```

Read the docs on all config values here: https://github.com/thecloudnativewebapp/GoCloudNative.Bff/wiki/Configuration

Note that currently, there is no Session-Timeout event. So for now, I advise to implementing automatic sign-out after a given idle-time in your front-end.

Hope this solves your problem!

Cheers,

Thanks again for your feedback!
