### ISSUE TITLE
Question: Choice of License

### ISSUE THREAD

**Issue by christophwille** [thecloudnativewebapp/GoCloudNative.Bff#33]
I know I am broaching a potential touchy subject - but I am always curious when libraries choose GPL (and in this special case: what if a BFF isn't only forwarding, but actually also doing something "else").

**Comment by appie2go** [comment]
Hi Cristoph,

I see your point and I am open to change the license.  I have two concerns which I would like the license to cover:

* Given this is a security-related product, and this is an open source product, I don't want any liability
* There are many vendors out there who are selling this kind of software. I want this software to be available for anyone, for free, and I don't want people to **sell** improved versions of our software that contain critical security improvements without sharing those with the community.

Would would be an appropriate license in that case?

**Comment by christophwille** [comment]
If you want to stay in the realm of OSS licenses, maybe https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License might be a good fit. However, that would not preclude someone using it in a hosted commercial project or building a library on top of it. This is where you'd have to leave the realm of approved OSS licenses, and eg go for something like https://www.linkedin.com/pulse/why-terraform-license-change-good-news-everyone-except-mike-hodgkins/ (I wouldn't comment on the "good news" part though, this was the first article that came up for me).

**Comment by appie2go** [comment]
It seems that LGPL makes sense in this case. I'm quite busy working on other features at the moment. Would you mind making a pull-request?

**Comment by christophwille** [comment]
To be legally safe, please look at https://github.com/icsharpcode/SharpZipLib/issues/103#issuecomment-206696820 and the thread following. Basically, you need the ok of every past contributor to change the license. (the various "I certify..." replies give you an idea how easy that actually is).

**Comment by appie2go** [comment]
That's not a problem. But we're having a meeting soon anyways. Because, as you may have noticed, none of us are legal experts, @yuriburger is deepdiving into the implications of everything to get it right in one go. More on that next week. 

Anyways, we're addressing the issue of people having to open source their implementations in one of the next versions. 

Stay tuned

**Comment by appie2go** [comment]
[License has been changed to LGPL](https://github.com/thecloudnativewebapp/GoCloudNative.Bff/commit/48514ce7be4718b483f92d07544402ac356c5e9f)

Thanks Christoph, for your feedback!

Cheers,
