### ISSUE TITLE
Add action on After Successful Login

### ISSUE THREAD

**Issue by Alism0** [thecloudnativewebapp/GoCloudNative.Bff#49]
Thank you for the project. Very cool! =)
Is it possible to add an action on an event after a successful login? Problem: i want to call a redirect to a route saved in the session

**Comment by appie2go** [comment]
Hi,

Glad I could help. You can already do this, if you want. The bff is designed to redirect to an endpoint after a succesful login. Configure the landingpage property: https://github.com/thecloudnativewebapp/GoCloudNative.Bff/wiki/Configuration#landingpage

Here's a quickstart: https://github.com/thecloudnativewebapp/GoCloudNative.Bff/wiki/Quickstarts#openid-connect

On a successful login you can redirect to an endpoint of your choice. You can use that endpoint todo anything you like, like redirecting, for example.

Hope this helps!

Cheers, and thanks for your feedback!

**Comment by Alism0** [comment]
Is it possible to dynamically change the landing page? After application configuration?

Anyway, the Landing page is a global setting, and I want to perform a redirect to a route (other than the landing page) without affecting the global application configuration)

**Comment by appie2go** [comment]
Are you looking for deep-linking functionality? Could you please describe your use-case in more detail?

**Comment by Alism0** [comment]
.Net solution with SPA in project (React template for [ASP.NET](http://asp.net/) Core).
Implemented automatic login to get static (wwwroot).
When trying to open a specific URL
<domain>/processes/{id},
a redirect to <domain> is performed (redirect_uri from keycloak).
With the help of an intermediate layer, it is possible to save the route “/processes/{id}” in the session.
After successful authentication and redirect to <domain>, I need to redirect to the path saved in the session.
Here is such a case)

**Comment by appie2go** [comment]
Let me see what i can do, i'll get back to you in a couple of days.

**Comment by appie2go** [comment]
Hi there,

I've just release v0.0.18, it contains the following functionality. I think this should be suitable for your use-case.

https://github.com/thecloudnativewebapp/GoCloudNative.Bff/wiki/Customization-and-extendability#implementing-a-custom-authentication-callback-handler

Cheers,

Thanks for your feedback
