### ISSUE TITLE
Add action on renew token error

### ISSUE THREAD

**Issue by Alism0** [thecloudnativewebapp/GoCloudNative.Bff#60]
Hi)
Thank you very much for your help with solving this issue:
https://github.com/thecloudnativewebapp/GoCloudNative.Bff/issues/49
I have a new case)
We have pre-authentication from Microsoft (SSO) in our infrastructure. Also, we have keycloak.
In the system, we use BFF. We connect to keycloak via OIDC.
When we access the site (the BFF), the BFF makes a redirect to keycloak. 
When we redirect to keycloak, we login to Microsoft via SSO. 
A session for the user “Regular SSO” is created in keycloak. 
Also, a “Offline” (30-day) user session is created. 
Once or twice, we successfully execute the refresh_token. 
Then, (after about ten minutes), keycloak return an error:
2023-10-05 08:21:26.1391|48|INFO|Yarp.ReverseProxy.Forwarder.HttpForwarder|RequestCreation: An error was encountered while creating the request message. System.ApplicationException: Unable to retrieve token. OIDC server responded BadRequest: {"error":"invalid_grant","error_description":"Offline user session not found"}
   at GoCloudNative.Bff.Authentication.OpenIdConnect.OpenIdConnectIdentityProvider.RefreshTokenAsync(String refreshToken)
   at GoCloudNative.Bff.Authentication.OpenIdConnect.TokenFactory.RenewAsync[T](String refreshToken, Int32 timeoutInSeconds)
   at GoCloudNative.Bff.Authentication.OpenIdConnect.TokenFactory.RenewAsync[T](String refreshToken, Int32 timeoutInSeconds)
   at GoCloudNative.Bff.Authentication.OpenIdConnect.TokenFactory.RenewAccessTokenIfExpiredAsync[T](Int32 timeoutInSeconds)
   at GoCloudNative.Bff.Authentication.HttpHeaderTransformation`1.<Apply>b__5_0(RequestTransformContext x)
   at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, String destinationPrefix, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, ForwarderRequestConfig requestConfig, Boolean isStreamingRequest, ActivityCancellationTokenSource activityToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)

Apparently, this happens because the user’s inactivity causes the expiry of the “Regular SSO” session.

The following solutions are being considered:
1 Extend “Regular SSO” by renewing the token. For example, try refresh_token rotation.
2 Extend “Regular SSO” with some artificial user actions. It is not clear how this can be done (token renewal is not considered a user action).
3 Increase the user idle timeout for “Regular SSO” sessions. However, there are many questions, including from information security (IS) side.
4 It is unclear how to update the token using the created “Offline” session... Whether through BFF or Keycloak. It does not seem like a correct solution either.
5 Catch this error in the middleware based on the code (502) and the text (“Offline user session not found”). Then, perform a redirect to Keycloak.

The 5th option seems like the most correct and sufficient. 
So I will try adding my own middleware to handle this error. However, I don’t particularly like the middleware solution in this case.

My question is: is there a planned library update that will have a plug-in point for handling keycloak error updates to the token? (by analogy with IAuthenticationCallbackHandler).
Perhaps you have any ideas for this case?)

Thanks)
PS: Perhaps in the future, it would be worth adding event handlers for user logout.

**Comment by appie2go** [comment]
Hi Alismo,

Thanks very much for your feedback. This is a good point. I will pick up this issue. Expect a fix for this issue in a week or so.

Cheers,

Albert

**Comment by Alism0** [comment]
UPD: The trigger for the completion of Regular SSO is not just the expiration of time, but the triggering of the “Renewed access_token and refresh_token” event (according to the logs). After this action, “Regular SSO” is completed and, when the next token update call is made, an error is returned.
Thanks, Supe... appie2go)

**Comment by appie2go** [comment]
It makes sense. A refresh_token is only valid for a valid period of time. After that time it would make sense to redirect the user to the /authorize endpoint or "sign him/her out". 

Difficulty is how to provide feedback to the front-end since this is an asynchrones process... It's an event.. Let me do some research and figure out how we can communicate to the front-end.

**Comment by Alism0** [comment]
Probably requires either additional research static refresh_tokens (if the old and new refresh_tokens are different) or to add configuring the enabling/disabling of the token revocation after the update if the old and new refresh_tokens are different.

**Comment by OleksiiSydorov** [comment]
> Found an issue with keycloak user session termination: Refresh tokens in keycloak update both access_token and refresh_token. Therefore, the code:
> 
> ```
> // in case of static refresh_tokens requesting a new access token will not always yield a refresh_token
> if (!string.IsNullOrEmpty(tokenResponse.refresh_token) && refreshToken != tokenResponse.refresh_token) 
> {
>     await _identityProvider.RevokeAsync(refreshToken);
> }
> ```
> 
> was always called. Revoking the old refresh_token led to the user session closing, so the next time there was an error "Offline user session not found". Solution: Implemented my own OpenIdConnectProvider with empty RevokeAsync.
> 
> Thanks for the extension methods) It’s great that everyone can add their own implementation.

so, how you exactly fixed this issue? 
Created own identity provider implementation with empty RevokeAsync? Could you specify more details?

**Comment by appie2go** [comment]
Hi there,

While building this software i used SOLID as a core principle. Meaning the Open/Close principle applies: Open for extention, closed for modification. This means classes contain virtual methods that are extendible so you can modify it to your needs.

I believe in your case you are using keycloak, right? Means that you are using OpenIdConnect. When you look into the repository, you will see that one of the key-classes that make this possible is the [OpenIdConnectIdentityProvider](https://github.com/thecloudnativewebapp/GoCloudNative.Bff/blob/main/src/GoCloudNative.Bff.Authentication.OpenIdConnect/OpenIdConnectIdentityProvider.cs) class.

What alismo did, is he derived from this class, like so:

```csharp

public class ExtendedOpenIdConnectProvider : GoCloudNative.Bff.Authentication.OpenIdConnect.OpenIdConnectIdentityProvider
{
  public override Task RevokeAsync(string token) {
     // do magic..
  
     return base.RevokeAsync(token);
  }
}

```

You can do the same for the other methods on the interface:

* GetAuthorizeUrlAsync
* GetTokenAsync
* RefreshTokenAsync
* RevokeAsync
* BuildEndSessionUri
* ObtainDiscoveryDocument

You can register your custom provider like so:

```csharp
builder.Services.AddBff(config, o =>
{
    o.RegisterIdentityProvider<ExtendedOpenIdConnectProvider, OpenIdConnectConfig>(config.Oidc);
});
```

Hope this answers your question?

**Comment by appie2go** [comment]
Hi @OleksiiSydorov 

I was browsing through issues and i saw i totally missed your last comment. I'm sorry about that! I hope your issue was solved and if not, can i still be of assistance?

Cheer,
