### ISSUE TITLE
Add an endpoint to the "account" controller to manually trigger the update of the access_token and resfresh_token

### ISSUE THREAD

**Issue by Alism0** [thecloudnativewebapp/GoCloudNative.Bff#78]
Hi)
In theory, it should be possible on the frontend side to trigger the token update before the access_token expires
Thanks

**Comment by appie2go** [comment]
Hi,

I assume the use-case is that you want to delegate the responsibility to refresh the access_token to the front-end? I'm not sure I agree there. The general idea should be that the consumer of this library should not have to worry about such things.

So, could you please describe the use-case?

Cheers,

**Comment by Alism0** [comment]
Next code:
https://github.com/thecloudnativewebapp/GoCloudNative.Bff/blob/main/src/GoCloudNative.Bff.Authentication/HttpHeaderTransformation.cs
What happens when multiple requests access the API concurrently when the token has expired? The lock in the Renew method of the 
https://github.com/thecloudnativewebapp/GoCloudNative.Bff/blob/main/src/GoCloudNative.Bff.Authentication/OpenIdConnect/TokenFactory.cs
code does not block the execution of other requests.
For example, a user can do something for 5 minutes on the page, then navigate to another component (React), from where N requests to the API are triggered.
As a result, the first request updates the tokens and executes, while the remaining N-1 return 401 errors.
The idea of 15 seconds is interesting, but it doesn’t solve the problem =)
Therefore, it would be good if it were possible to manually update the token from the front before making requests.
At least until a solution is found to block execution during the update process.
P.S. It would also be useful to add the ability to configure this period (these 15 seconds, for some people it may be enough).
Thanks)

**Comment by Alism0** [comment]
Sorry, did not see the code below: there is a mechanism for waiting for requests. 
However

```
var cacheKey = $"refreshing_token_{_session.Id}";
var valueInSession = _session.GetString(cacheKey);
var isWorking = !string.IsNullOrEmpty(valueInSession);

// The first request in a session which needs a renewed access token will bump into this block
if (!isWorking)
{
    _session.SetString(cacheKey, "true");
...
}
```

It does n’t look 100% reliable. It seems like several requests could slip through and go to update the token. 
Anyhow, regarding the endpoint for updating, everyone can implement their own endpoint, 
by following the example in: 
(https://github.com/thecloudnativewebapp/GoCloudNative.Bff/blob/main/src/GoCloudNative.Bff.Authentication/Endpoints/Endpoints.cs)
They will only have to replicate the UpdateAccessAndRefreshTokenAsync logic from the session extension methods in:
https://github.com/thecloudnativewebapp/GoCloudNative.Bff/blob/main/src/GoCloudNative.Bff.Authentication/ISessionExtensions.cs

Thanks again)

**Comment by appie2go** [comment]
Hi, 

Intend to close this issue, I've split it into two other issues:

* https://github.com/thecloudnativewebapp/GoCloudNative.Bff/issues/80
* https://github.com/thecloudnativewebapp/GoCloudNative.Bff/issues/81

The issues you've reported have a bit more impact than i anticipated on. Please stay tuned though, we're working on it :-)

Cheers,

Thanks again for your feedback
