### ISSUE TITLE
Remove the automatic addition of the offline_access claim

### ISSUE THREAD

**Issue by Alism0** [thecloudnativewebapp/GoCloudNative.Bff#79]
Hello again)
I think this should be monitored by the developer, but it should be described in the documentation that this parameter needs to be added for create Offline Token. But maybe I’m wrong.)
Thanks

**Comment by appie2go** [comment]
Hi!

The offline_access scope is required to obtain a refresh token. (Read more here: https://github.com/thecloudnativewebapp/GoCloudNative.Bff/issues/27)

Adding more documentation on the topic might not be a bad idea given that this is a recurring question. 

Cheers,

**Comment by Alism0** [comment]
Is there a link to documentation on 3rd-party cookie issues for obtaining a token? 
Or was it empirically determined?

**Comment by Alism0** [comment]
Solution:
Everyone can implement their own Identity provider and set the required scope in it for experiments)
Thanks

**Comment by appie2go** [comment]
Hi,

Sorry for the late reply. This package was built with extensibility in mind. Glad to see it serves it's purpose in this use-case. :-) 

I'm closing this issue.

Thanks again for your feedback.
